services: 
"  - type: web" 
"    name: ecoprograms" 
"    env: python" 
"    buildCommand: \"pip install -r requirements.txt\"" 
"    startCommand: \"gunicorn sap.sap.wsgi:application\"
" 
"    envVars:" 
"      DJANGO_SETTINGS_MODULE: \"sap.settings\"" 
"      PYTHON_VERSION: \"3.11\"" 
